# Generated by Django 3.2.8 on 2021-12-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProgramm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, verbose_name='Введите слово')),
            ],
        ),
    ]
