# Generated by Django 3.2.8 on 2021-12-22 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyProgramm', '0002_word'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='word',
            new_name='full_word',
        ),
    ]
