# Generated by Django 3.2.8 on 2021-12-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProgramm', '0003_rename_word_word_full_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_text', models.TextField(verbose_name='Форматированный текст')),
            ],
            options={
                'verbose_name': 'Форматированный текст',
                'verbose_name_plural': 'Форматированные текста',
            },
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'verbose_name': 'Текст', 'verbose_name_plural': 'Текста'},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'verbose_name': 'Слово', 'verbose_name_plural': 'Слова'},
        ),
    ]
